### ISSUE TITLE
Required option not passed: access_token

### ISSUE THREAD

**Issue by mseshachalam** [thephpleague/oauth2-facebook#1]
access_token Array ( [{"access_token":"CAANRd19hkIEBAFi0xl7xHDExRnp2ZCh8uzbyJnZCsybKVMMmUjvHXmYcDys5WcSHLlE1l1GAafPCIOMZCLvalHcD5NT1OCrecMWsvyoJvp4oc80ThsPbGtbGrBABTarpOX2608FZAscDKOytuk1fbfOXeZCTxg5hn16y373trZCdIcuEjbUzM2zkDA8NgLZCCZCfkEpZAyZBYa3NNjL46ajvpz","token_type":"bearer","expires_in":5162661}] => )

the structure seems wrong for facebook.
I had to do the following in getAccessToken to get rid of above exception
```
$result = $this->prepareAccessTokenResult($result);
$result = array_keys($result);
return $grant->handleResponse(json_decode($result[0], true));

```

**Comment by SammyK** [comment]
Ah yes, this is the new return type for Graph v2.3. I'll make sure to get a fix for this rocking soon. :)

**Comment by SammyK** [comment]
This should be fixed in `0.0.3`. Let me know if you have any more trouble with it! :)

**Comment by mseshachalam** [comment]
composer gives dependency error when used 0.0.3 with "league/oauth2-google": "0.1.0"

**Comment by SammyK** [comment]
This provider is for [OAuth 2.0 Client v1.0](https://github.com/thephpleague/oauth2-facebook#installation). If you need to use v0.x, there is [already a Facebook provider included](https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/Facebook.php) in that version.

**Comment by mseshachalam** [comment]
I am not sure if I understand it. I need to use the oauth2-google and oauth2-facebook. right now with any combination of these package versions, I get a dependency error because of the oauth2-client. Can you please the composer lines for oauth2-google and oauth2-facebook ? :)

**Comment by SammyK** [comment]
It looks like [oauth2-google is using the 0.x version of OAuth 2.0 Client](https://github.com/thephpleague/oauth2-google/blob/master/composer.json#L22) which is weird because there is already [a Google provider in the 0.x branch](https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/Google.php).

So what I would do in your case is remove the dependancies for oauth2-google and oauth2-facebook from your composer.json and keep using the oauth2-client 0.x version since it comes with both Facebook and Google providers.

Then when oauth2-client v1.0 is stable, upgrade to v1.0 and add the oauth2-google and oauth2-facebook packages to your composer.json.

**Comment by mseshachalam** [comment]
Thanks

**Comment by ramsey** [comment]
@SammyK Maybe oauth2-google is targeting 0.x because 1.0 is still a moving target?

**Comment by SammyK** [comment]
@ramsey Probably true. :) I just assumed that these external provider repos were all for 1.0 since 0.0 has them included (at least for Facebook & Google anyway).

**Comment by ramsey** [comment]
Good point. I'm trying to get us to 1.0 soon! :-)

**Comment by SammyK** [comment]
You're doing a great job - keep up the good work! :)

**Comment by new-uname** [comment]
jb,/
