### ISSUE TITLE
wrong function name in FacebookUser.php ?

### ISSUE THREAD

**Issue by dsp1986** [thephpleague/oauth2-facebook#11]
I needed to change line 139
from: 
public function asArray()
to:
public function toArray()

to comply with declarations in ResourceOwnerInterface. Example code from did not work otherwise.
should I fork, correct and do a pull request?
I am not sure yet whether this will break anything else.

**Comment by ramsey** [comment]
@SammyK, for some background, `toArray()` was previously not part of the `ResourceOwnerInterface`. We added it in 1.0.0-beta2, since many providers already had a `toArray()`, which only the Facebook one using `asArray()`. Sorry for the confusion.

See also: https://github.com/thephpleague/oauth2-client/blob/master/CHANGELOG.md#100-beta2

**Comment by SammyK** [comment]
This was already taken care of [in Alpha 2](https://github.com/thephpleague/oauth2-facebook/blob/master/CHANGELOG.md#100-alpha-2---august-10-2015).

Now that 1.0 is out, I can do a 1.0 of the Facebook provider! :)
