### ISSUE TITLE
After authorization - 500 Internal Server error

### ISSUE THREAD

**Issue by axadr** [thephpleague/oauth2-facebook#39]
It happens when graphApiVersion < 2.8 
The problem is in Facebook.php
```
function getResourceOwnerDetailsUrl
        ...
        // backwards compatibility less than 2.8
        if ((float) substr($this->graphApiVersion, 1) < 2.8) {
            $fields[] = 'bio';
        } 
```
Regardless of the version of graphApi you want, facebook redirects to v2.9. 
Perhaps it is Facebook's bug. I don't know.

**Comment by SammyK** [comment]
Hey @axadr! Are you still getting this error? It sounds like a bug on Facebook's side if it's a 500 error. You'd have to submit the bug via their [support site](https://developers.facebook.com/bugs/).

**Comment by luceos** [comment]
The issue is the following, the bio field is deprecated and throws a warning if requested from 2.8 onward. The logic in the [Facebook Provider](https://github.com/thephpleague/oauth2-facebook/blob/1.x/src/Provider/Facebook.php#L110-L112) actually checks whether the configured Graph api version is (only) less than 2.8:

```php
        // backwards compatibility less than 2.8
        if (version_compare(substr($this->graphApiVersion, 1), '2.8') < 0) {
            $fields[] = 'bio';
        }
```
Version compare returns -1 if the configured graph version is lower than 2.8, 0 when it's equal and 1 if higher. As such the current code will add the bio field in the request when having 2.8 as graph api version configured. Facebook api will throw a deprecated warning and thus an IdentityProviderException which is (gracefully) handled by the package.


Detailed trace from our [facebook driver for Flarum](https://github.com/flarum/flarum-ext-auth-facebook/blob/master/src/FacebookAuthController.php#L46)

![image](https://user-images.githubusercontent.com/504687/36856516-79a33738-1d76-11e8-9ca1-469c153ee89c.png)

**Comment by shadowhand** [comment]
The `graphApiVersion` can be used to set the correct graph version.
